[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts-upgradeable" = "5.0.1"
"@openzeppelin-contracts" = "5.0.1"

# Network configurations
[rpc_endpoints]
avalanche_mainnet = "${AVALANCHE_MAINNET_RPC}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC}"
local = "http://localhost:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
